apiVersion: apps/v1
kind: Service
metadata:
        name: psweb
spec:
    selector:
            env: staging 
            version: v1 
            projet: devops-training
    type: NodePort
    ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31071
~                                                                               
~                     
